### ISSUE TITLE
renewal fails with ConnectionError: ('Connection aborted.', BadStatusLine("''",))

### ISSUE THREAD

**Issue by apk** [kuba/simp_le#111]
When trying to renew a cert I get this error:

```
2016-06-10 05:42:24,094:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Traceback (most recent call last):
  File "/data/krey/simp_le/simp_le.py", line 1401, in main
    return main_with_exceptions(cli_args)
  File "/data/krey/simp_le/simp_le.py", line 1386, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/data/krey/simp_le/simp_le.py", line 1282, in persist_new_data
    client = registered_client(args, existing_data.account_key)
  File "/data/krey/simp_le/simp_le.py", line 1230, in registered_client
    regr = client.register(new_reg)
  File "/data/krey/simp_le/venv/local/lib/python2.7/site-packages/acme/client.py", line 98, in register
    response = self.net.post(self.directory[new_reg], new_reg)
  File "/data/krey/simp_le/venv/local/lib/python2.7/site-packages/acme/client.py", line 650, in post
    response = self._send_request('POST', url, data=data, **kwargs)
  File "/data/krey/simp_le/venv/local/lib/python2.7/site-packages/acme/client.py", line 609, in _send_request
    response = requests.request(method, url, *args, **kwargs)
  File "/data/krey/simp_le/venv/local/lib/python2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/krey/simp_le/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/krey/simp_le/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/data/krey/simp_le/venv/local/lib/python2.7/site-packages/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

A few seconds elapse between 'Starting new' and the backtrace. Timeouts too short somewhere?

I'm using webroot with the twist that I'm not running on the actual server but instead having a proxy_pass for the location. But I don't even get an access there.

On the last round this problem went away when I tried again next morning, but this didn't work this time.

**Comment by kuba** [comment]
Do you still experience this issue? I haven't looked closely, but it looks like it's gonna be hard to debug on my side.

**Comment by apk** [comment]
Unfortunately I still have this issue - and I'm slightly afraid that it's not actually a client issue.

When I try it the first time the time between the

```
2016-06-12 19:11:38,660:DEBUG:root:605: Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-reg. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "zzqheyD
```

and the error traceback is a bit longer (a dozen seconds or so), on subsequent executions it's shorter.

I'm not a python person, but I'm going to try to sprinkle a few print in the code to see where it excepts.

A client-side timeout should look different to this?

**Comment by apk** [comment]
By now indeed sounds like server-side. I did now let it try every half hour, and after about a dozen attempts it went through.

**Comment by apk** [comment]
So, I was sufficiently frustrated (having this problem again on the next cert round) that I forwarded the .well-known to yet another machine, and installed simp_le there - and it worked.

Either arm vs. x86 makes a difference, or there is something broken with that banana pi.

**Comment by ppKrauss** [comment]
See also https://github.com/certbot/certbot/issues/2677
