### ISSUE TITLE
Invalid client.revoke() call

### ISSUE THREAD

**Issue by jeaye** [kuba/simp_le#120]
It looks like we're only passing the cert to `client.revoke`, but it also expects a reason. The current simp_le version:

https://github.com/kuba/simp_le/blob/master/simp_le.py#L1331

The official docs:

http://letsencrypt.readthedocs.io/projects/acme/en/latest/api/client.html#acme.client.Client.revoke

This is manifesting, for me, when trying to revoke a cert:

```bash
$ simp_le --revoke -f cert.pem 
2017-04-22 18:52:28,651:INFO:simp_le:1211: Generating new account key
Traceback (most recent call last):
  File "/nix/store/vdp6dn3shkwd2yihdbzxs8zvv1sa99gd-simp_le-client-0.1.1/lib/python2.7/site-packages/simp_le.py", line 1401, in main
    return main_with_exceptions(cli_args)
  File "/nix/store/vdp6dn3shkwd2yihdbzxs8zvv1sa99gd-simp_le-client-0.1.1/lib/python2.7/site-packages/simp_le.py", line 1374, in main_with_exceptions
    return revoke(args)
  File "/nix/store/vdp6dn3shkwd2yihdbzxs8zvv1sa99gd-simp_le-client-0.1.1/lib/python2.7/site-packages/simp_le.py", line 1331, in revoke
    client.revoke(existing_data.cert)
TypeError: revoke() takes exactly 3 arguments (2 given)

Unhandled error has happened, traceback is above

Debugging tips: -v improves output verbosity. Help is available under --help.
```

**Comment by zenhack** [comment]
@jeaye, this is fixed on my fork:

<https://github.com/zenhack/simp_le>

This repository seems to be abandoned; @kuba has been inactive on Github since June of last year. The reason parameter was introduced in python-acme 0.11, which was released some time after this repo was abandoned.

**Comment by jeaye** [comment]
On Sat, Apr 22, 2017 at 12:27:08PM -0700, Ian Denhardt wrote:
> @jeaye, this is fixed on my fork:
> 
> <https://github.com/zenhack/simp_le>
> 
> This repository seems to be abandoned; @kuba has been inactive on Github since June of last year. The reason parameter was introduced in python-acme 0.11, which was released some time after this repo was abandoned.

Yep, I've found that, thanks. The issue is that NixOS is currently pointing at 0.1.1 of your fork (which still has this issue), not 0.2.0: https://github.com/mayflower/nixpkgs/blob/master/pkgs/tools/admin/simp_le/default.nix I'm currently testing out 0.2.0 before making a PR/issue in nixpkgs.

Thanks again.

**Comment by zenhack** [comment]
Worth noting, 0.1.1 specifies an upper bound on the version of python-acme, specifically because of compatibility issues like this; If you're hitting this issue it's because you're using incompatible versions.

**Comment by jeaye** [comment]
On Sat, Apr 22, 2017 at 12:31:57PM -0700, Ian Denhardt wrote:
> Worth noting, 0.1.1 specifies an upper bound on the version of python-acme, specifically because of compatibility issues like this; If you're hitting this issue it's because you're using incompatible versions.

Yep, I think that's because someone did this: https://github.com/mayflower/nixpkgs/blob/master/pkgs/tools/admin/simp_le/default.nix#L15

Grr.

**Comment by zenhack** [comment]
I really wish distro packagers would report (perceived) bugs like this upstream more reliably... Grr indeed.
