### ISSUE TITLE
Infinite connection loop while generating new (not renewed) cert

### ISSUE THREAD

**Issue by lwatsondev** [kuba/simp_le#17]
```
2015-12-03 15:39:02 [INFO] Creating certificate for gitlab.notoriousdev.com
2015-12-03 15:39:02 [INFO] Running simp_le from /etc/ssl/letsencrypt/certs/gitlab.notoriousdev.com as: simp_le --cert_key_size 2048 --email redacted@notoriousdev.com --server https://acme-v01.api.letsencrypt.org/directory --default_root /etc/letsencrypt/webrootauth -f key.pem -f cert.pem -f chain.pem -f fullchain.pem -d gitlab.notoriousdev.com -d gitlab.ndev.me
2015-12-03 20:39:02,972:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-03 20:39:03,945:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-03 20:39:04,093:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-03 20:39:04,284:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-03 20:39:04,514:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-03 20:39:04,765:INFO:requests.packages.urllib3.connectionpool:207: Starting new HTTP connection (1): gitlab.ndev.me
2015-12-03 20:39:04,921:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): gitlab.notoriousdev.com
2015-12-03 20:39:05,483:WARNING:simp_le:801: gitlab.ndev.me was not successfully verified by the client. CA is likely to fail as well!
2015-12-03 20:39:05,499:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-03 20:39:05,709:INFO:requests.packages.urllib3.connectionpool:207: Starting new HTTP connection (1): gitlab.notoriousdev.com
2015-12-03 20:39:05,797:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): gitlab.notoriousdev.com
2015-12-03 20:39:06,309:WARNING:simp_le:801: gitlab.notoriousdev.com was not successfully verified by the client. CA is likely to fail as well!
2015-12-03 20:39:06,322:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-03 20:39:06,760:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-03 20:39:06,881:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-03 20:39:11,030:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-03 20:39:11,182:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-03 20:39:15,333:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-03 20:39:15,470:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-03 20:39:19,737:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-03 20:39:19,895:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Traceback (most recent call last):
  File "/opt/simp_le/venv/bin/simp_le", line 9, in <module>
    load_entry_point('simp-le', 'console_scripts', 'simp_le')()
  File "/opt/simp_le/simp_le.py", line 871, in main
    raise SystemExit(_main(cli_args))
  File "/opt/simp_le/simp_le.py", line 864, in _main
    _new_data(args)
  File "/opt/simp_le/simp_le.py", line 809, in _new_data
    certr, _ = client.poll_and_request_issuance(csr, authorizations.values())
  File "/opt/simp_le/venv/local/lib/python2.7/site-packages/acme/client.py", line 366, in poll_and_request_issuance
    time.sleep(seconds)
KeyboardInterrupt
```

Without the keyboard interrupt, the new HTTPS connection message just repeats forever.

In the interest of transparency, I am using a wrapper script, but this shouldn't affect anything as the only thing this script does is generate a simp_le command based on variables and runs it. The final command that gets ran is printed in the log.

This problem only started a few hours into the public beta launch today, simp_le was working perfectly before that. I've also tested it under the following conditions and everything works as expected.
- Existing cert that doesn't need renewing. (skips)
- Attempting to generate a new cert while rate limited (fails, as expected, but doesn't get stuck in a connection loop).

It's only when generating a completely new cert for a domain that hasn't had a cert with Let's Encrypt yet that this problem occurs.

Let me know if there's more info I could provide.

**Comment by kuba** [comment]
Thanks for the report. This loop likely means that your `AuthorizationResource` turned into `STATUS_INVALID` (you didn't specify correct `public_html` or something similar) - try running with `-v` to see if simple verification works (https://github.com/kuba/simp_le/blob/c14ec05600c56fabe9b539f39bfcb2cc6a448003/simp_le.py#L797). The loop should quit as soon as such condition happens and I have fixed this in https://github.com/letsencrypt/letsencrypt/pull/1635. #18 should move us to latest version of `acme` library.

**Comment by lwatsondev** [comment]
Edit: disregard everything, I'm an idiot.

It was the webroot this time around.
