### ISSUE TITLE
PollError traceback

### ISSUE THREAD

**Issue by ThomasWaldmann** [kuba/simp_le#26]
When running this on the server:

```
env/bin/simp_le -f fullchain.pem -f key.pem \
                -d nsupdate.info -d www.nsupdate.info -d ipv4.nsupdate.info -d ipv6.nsupdate.info \
                --default_root /my/htdocs \
                --cert_key_size 2048 --email my@email
```

I get that:

```
2015-12-04 12:41:57,641:INFO:simp_le:157: Creating new account key
2015-12-04 12:41:59,567:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-04 12:41:59,956:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-04 12:42:00,162:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-04 12:42:00,387:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): letsencrypt.org
2015-12-04 12:42:02,743:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-04 12:42:04,992:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-04 12:42:06,244:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-04 12:42:08,494:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-04 12:42:10,752:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-04 12:42:11,994:INFO:requests.packages.urllib3.connectionpool:207: Starting new HTTP connection (1): httprelay.int.thinkmo.de
2015-12-04 12:42:11,996:WARNING:simp_le:801: ipv6.nsupdate.info was not successfully verified by the client. CA is likely to fail as well!
2015-12-04 12:42:12,009:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-04 12:42:14,247:INFO:requests.packages.urllib3.connectionpool:207: Starting new HTTP connection (1): httprelay.int.thinkmo.de
2015-12-04 12:42:14,248:WARNING:simp_le:801: nsupdate.info was not successfully verified by the client. CA is likely to fail as well!
2015-12-04 12:42:14,261:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-04 12:42:16,500:INFO:requests.packages.urllib3.connectionpool:207: Starting new HTTP connection (1): httprelay.int.thinkmo.de
2015-12-04 12:42:16,502:WARNING:simp_le:801: www.nsupdate.info was not successfully verified by the client. CA is likely to fail as well!
2015-12-04 12:42:16,514:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-04 12:42:18,760:INFO:requests.packages.urllib3.connectionpool:207: Starting new HTTP connection (1): httprelay.int.thinkmo.de
2015-12-04 12:42:18,762:WARNING:simp_le:801: ipv4.nsupdate.info was not successfully verified by the client. CA is likely to fail as well!
2015-12-04 12:42:18,774:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-04 12:42:20,015:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-04 12:42:22,231:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-04 12:42:24,436:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-04 12:42:26,645:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Traceback (most recent call last):
  File "env/bin/simp_le", line 9, in <module>
    load_entry_point('simp-le==0.0.0', 'console_scripts', 'simp_le')()
  File "/srv/nsupdate.info/simp_le/simp_le/simp_le.py", line 874, in main
    raise SystemExit(_main(cli_args))
  File "/srv/nsupdate.info/simp_le/simp_le/simp_le.py", line 867, in _main
    _new_data(args)
  File "/srv/nsupdate.info/simp_le/simp_le/simp_le.py", line 812, in _new_data
    max_attempts=(10 * len(authorizations)))
  File "/srv/nsupdate.info/simp_le/env/local/lib/python2.7/site-packages/acme/client.py", line 383, in poll_and_request_issuance
    raise errors.PollError(waiting, updated)
acme.errors.PollError
```

So, it says "not successfully verified" some times, but not WHY.

Also, the PollError, should it be catched and a good error msg be given?

The web server is behind a https reverse proxy, could that be a problem?

**Comment by kuba** [comment]
There are two possible reasons
- timeout (`PollError.timeout`)
- Authorization is `STATUS_INVALID` (`not PollError.timeout`), which likely means that your HTTP server didn't host the right stuff - rerun client with `-v` to see if simple verification succeeds.

Yes, this error should be caught. I'll fix in a couple of hours.

**Comment by gillesdemey** [comment]
I'm also getting the same error, using an NGINX https reverse proxy. Could this be causing the problem?

**Comment by ThomasWaldmann** [comment]
@kuba don't think it is a timeout. happens always.

but i found that part of the problem was permissions on the directories / files it creates.
"umask 002" helped.

it still does not work as it seems to want to talk to itself (as opposed to the acme server) which does not work here (from the "inside"). why is that needed?

```
requests.packages.urllib3.connectionpool:387: "GET http://ipv4.nsupdate.info/.well-known/acme-challeng
e/9xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxg HTTP/1.1" 403 None
```

**Comment by ThomasWaldmann** [comment]
another part of the problem is that the acme server still does not work with ip v6 and one of the domains in the cert is v6 only. this is sad, as I already reported that problem almost 1 year ago. :-(

besides that, due to my debugging, the server ran into rate limiting:

```
2015-12-05 01:31:48,541:ERROR:simp_le:879: ACME server returned an error: urn:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new cert :: Too many certificates already issued for: nsupdate.info
```

So I'll stop debugging this now and hope that the ratelimit will not persist.

**Comment by kuba** [comment]
@ThomasWaldmann, before talking to a CA client will try to self-verify the challenge - errors are good indication that the CA will be unable to successfully validate your authorization. `403` in this case is a good example.

`umask` is a good tip, we should put it into wiki. Slight problem is that generated `account_key.json` and `key.{pem,der}` will also be subject to that umask, so we should advise users to `chmod 700 $CWD` - problem with that however is that webserver must be able to enter this directory, so it should be the owner, but this way risks unnecessarily exposing `account_key.json`. We should probably discuss it in #29.

IPv6 doesn't work indeed. For anyone interested, this is tracked in https://github.com/letsencrypt/letsencrypt/issues/180.

Most of the rate limits are reset weekly.

**Comment by skorokithakis** [comment]
@ThomasWaldmann Another thing I noticed is that `simp_le` doesn't put the files into the dir you specify, it puts them in `dir/.well-known/acme-challenges/`. Something to watch out for, as I aliased that URL into the dir directly.

**Comment by kuba** [comment]
This should be fixed in 768f166

**Comment by skorokithakis** [comment]
I can confirm this is fixed for me.

**Comment by gillesdemey** [comment]
This also solved the problem for me, thanks!
