### ISSUE TITLE
PollError

### ISSUE THREAD

**Issue by octfx** [kuba/simp_le#47]
Tried to get a new cert, got the following error:

```
2015-12-15 21:57:55,264:INFO:simp_le:159: Creating new account key
2015-12-15 21:57:55,726:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-15 21:57:55,997:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-15 21:57:56,259:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-15 21:57:56,529:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): letsencrypt.org
2015-12-15 21:57:57,643:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-15 21:57:57,905:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-15 21:57:58,176:INFO:requests.packages.urllib3.connectionpool:207: Starting new HTTP connection (1): <domain>
2015-12-15 21:57:58,204:INFO:simp_le:805: <domain> was successfully verified by the client
2015-12-15 21:57:58,213:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-15 21:57:58,990:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Unhandled error has happened:
Traceback (most recent call last):
  File "/opt/simp_le/simp_le.py", line 877, in main
    raise SystemExit(_main(cli_args))
  File "/opt/simp_le/simp_le.py", line 869, in _main
    _new_data(args)
  File "/opt/simp_le/simp_le.py", line 814, in _new_data
    max_attempts=(10 * len(authorizations)))
  File "/opt/simp_le/venv/local/lib/python2.7/site-packages/acme/client.py", line 383, in poll_and_request_issuance
    raise errors.PollError(waiting, updated)
PollError
```

Installed simp_le a few days ago and never had an issue with it

**Comment by kuba** [comment]
You must be using some old version (lines don't match with current `master`, e.g. https://github.com/kuba/simp_le/blob/master/simp_le.py#L814), please `git pull`.
