### ISSUE TITLE
wrapped/unwrapped OpenSSL problem

### ISSUE THREAD

**Issue by xrchz** [kuba/simp_le#70]
My first try running `simp_le`, it successfully verified with the CA and generated the certificate, but crashed before returning it to me. Traceback:

```


Traceback (most recent call last):
  File "/usr/bin/simp_le", line 1407, in main
    return main_with_exceptions(cli_args)
  File "/usr/bin/simp_le", line 1392, in main_with_exceptions
    new_data(args, existing_data)
  File "/usr/bin/simp_le", line 1322, in new_data
    certr = get_certr(client, csr, authorizations)
  File "/usr/bin/simp_le", line 1259, in get_certr
    max_attempts=(10 * len(authorizations)))
  File "/usr/lib/python3.5/site-packages/acme/client.py", line 386, in poll_and_request_issuance
    return self.request_issuance(csr, updated_authzrs), updated_authzrs
  File "/usr/lib/python3.5/site-packages/acme/client.py", line 310, in request_issuance
    headers={'Accept': content_type})
  File "/usr/lib/python3.5/site-packages/acme/client.py", line 631, in post
    data = self._wrap_in_jws(obj, self._get_nonce(url))
  File "/usr/lib/python3.5/site-packages/acme/client.py", line 508, in _wrap_in_jws
    jobj = obj.json_dumps().encode()
  File "/usr/lib/python3.5/site-packages/acme/jose/interfaces.py", line 189, in json_dumps
    return json.dumps(self, default=self.json_dump_default, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/site-packages/acme/jose/interfaces.py", line 214, in json_dump_default
    return python_object.to_partial_json()
  File "/usr/lib/python3.5/site-packages/acme/jose/json_util.py", line 263, in to_partial_json
    return self.fields_to_partial_json()
  File "/usr/lib/python3.5/site-packages/acme/jose/json_util.py", line 251, in fields_to_partial_json
    jobj[field.json_name] = field.encode(value)
  File "/usr/lib/python3.5/site-packages/acme/jose/json_util.py", line 96, in encode
    return self.fenc(value)
  File "/usr/lib/python3.5/site-packages/acme/jose/json_util.py", line 401, in encode_csr
    OpenSSL.crypto.FILETYPE_ASN1, csr.wrapped))
AttributeError: 'X509Req' object has no attribute 'wrapped'

Unhandled error has happened, traceback is above
```

Information I got on IRC:

```
06:18:22   bmw | Looks like it's a simp_le bug, not a python-acme bug.
06:19:03   bmw | To try and shorten a long story, python-acme wraps OpenSSL cert and req objects in a wrapper class for convenience.
06:20:14   bmw | Recently, we found out that the module was sloppy in how it passed around those objects, using the wrapped/OpenSSL version interchangeably.
06:20:46   bmw | This caused bugs which was recently fixed in the python-acme. simp_le is using the OpenSSL object when it should be using the wrapped object.
06:21:08   bmw | We should file an issue about this on simp_le. Would you like to do it or would you like me to?
06:21:21   bmw | Also, as for simply using simp_le, you can try downgrading your python-acme version to 0.1.1.
```

**Comment by kuba** [comment]
Trying to pattern match the line numbers (and content) from the traceback, I see that:

```
75b55176 acme/acme/jose/json_util.py        (Brad Warren  2015-12-23 19:09:05 -0500 401)         OpenSSL.crypto.FILETYPE_ASN1, csr.wrapped))
```

https://github.com/letsencrypt/letsencrypt/commit/75b55176 was new in 0.2.0 release. https://github.com/kuba/simp_le/blob/c733594addd99d760f44884219a5b18b204033a8/setup.py#L12 shows that `simp_le` requires `0.1.0`.

@xrchz, you must have had updated `acme` yourself. Moreover, it's disturbing that you have `/usr/bin/simp_le`, rather than using virtualenv as suggested in the docs. Since you're not using supported setup, I'll close this bug for now, sorry!

@bmw, thanks for support :)

**Comment by zx2c4** [comment]
Any plans to support the latest 0.3.0 upstream?

**Comment by kuba-is-a-cunt** [comment]
Hey, @kuba my dear friend. I just had the EXACT SAME ISSUE as the original requester. Oh and yes, I didn't do a virtualenv, "as suggested by the docs". Sorry, but we don't all use the Nazi setup that you would like to prefer. If your software is written so poorly that it doesn't catch such errors and just barfs, it's a PIECE OF SHIT. Your failure to acknowledge that makes you an utter cunt and asshole. Which is why I'm not going to bother with the fucking abomination that simp_le is anymore and go down an alternative route. Fix your garbage software you fucking asshole and at least pretend that you care for bugs filed against it. If you can't, I politely suggest that you DIAF. Thanks!

**Comment by xrchz** [comment]
Now `acme` is up to `0.8.0`. Is `simp_le` still insisting on `0.1.1`?
