### ISSUE TITLE
Unexpected keyword argument 'new_authz_uri'

### ISSUE THREAD

**Issue by b0x42** [kuba/simp_le#87]
Hi,

I am getting an error while generating a new certificate.I am quite in the dark when it comes to interpret this error. 
I am very looking forward to getting any tips regarding this issue.

Thank you!

`2016-03-21 11:28:10,405:INFO:requests.packages.urllib3.connectionpool:735: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-03-21 11:28:10,673:DEBUG:requests.packages.urllib3.connectionpool:383: "POST /acme/reg/931843 HTTP/1.1" 202 917
2016-03-21 11:28:10,676:DEBUG:root:611: Received <Response [202]>. Headers: {'content-length': '917', 'expires': 'Mon, 21 Mar 2016 11:28:10 GMT', 'server': 'nginx', 'connection': 'keep-alive', 'link': '<https://acme-v01.api.letsencrypt.org/acme/new-authz>;rel="next", <https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf>;rel="terms-of-service"', 'pragma': 'no-cache', 'cache-control': 'max-age=0, no-cache, no-store', 'date': 'Mon, 21 Mar 2016 11:28:10 GMT', 'content-type': 'application/json', 'replay-nonce': 'dEgBfHbb9AlKjJftZlf7UU2gcyWEC_bbs5UV4dmimTg'}. Content: '{"id":931843,"key":{"kty":"RSA","n":"p9zDvdA4Nz1mRboTt_qDQcsA21jDbzXRY-pm_dPjPFpy8FsZ0eAaSJw4b_vG2XFr089OHIZ7p9em66rhgNX--ARuqUNURtbhzYyCxlkyoYrgC…","e":"AQAB"},"contact":["mailto:ben@my-domain.de"],"agreement":"https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf","initialIp":"128.136.16.34","createdAt":"2016-03-21T11:28:09Z"}'
2016-03-21 11:28:10,676:DEBUG:acme.client:636: Storing nonce: 'tH\x01|v\xdb\xf4\tJ\M\xa0s%\x84\x0b\x95\x15\xe1\xd9\xa2\x998'
2016-03-21 11:28:10,677:DEBUG:acme.client:551: Received response <Response [202]> (headers: {'content-length': '917', 'expires': 'Mon, 21 Mar 2016 11:28:10 GMT', 'server': 'nginx', 'connection': 'keep-alive', 'link': '<https://acme-v01.api.letsencrypt.org/acme/new-authz>;rel="next", <https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf>;rel="terms-of-service"', 'pragma': 'no-cache', 'cache-control': 'max-age=0, no-cache, no-store', 'date': 'Mon, 21 Mar 2016 11:28:10 GMT', 'content-type': 'application/json', 'replay-nonce': 'dEgBfHbb9A…mTg'}): '{"id":11321843,"key":{"kty":"RSA","n":"p9zDvdA4Nz1mRboTt_qDQcsA21jDbzXRY-pm_dPjPFpy8FsZ0eAaSJw4b_vG2XFr089OHIZ7p9em66rhgNX--ARuqUNURtbhzYyCxlkyoYrgC…","e":"AQAB"},"contact":["mailto:ben@my-domain.de"],"agreement":"https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf","initialIp":"128.136.16.34","createdAt":"2016-03-21T11:28:09Z"}'
Traceback (most recent call last):
  File "/usr/local/sbin/simp_le", line 1390, in main
    return main_with_exceptions(cli_args)
  File "/usr/local/sbin/simp_le", line 1375, in main_with_exceptions
    new_data(args, existing_data)
  File "/usr/local/sbin/simp_le", line 1276, in new_data
    for vhost in args.vhosts
  File "/usr/local/sbin/simp_le", line 1276, in <genexpr>
    for vhost in args.vhosts
TypeError: request_domain_challenges() got an unexpected keyword argument 'new_authz_uri'`

**Comment by kuba** [comment]
Are you using [virtualenv setup as described in README.rst](https://github.com/kuba/simp_le#installation)? Binary in `/usr/local/sbin/` suggests that you installed this software globaly, mixing up packages from PyPI with OS packages (do you have acme debian package installed?). I'm sorry to hear that you're having problems, but I don't see anything wrong on the software side, so I'm gonna close this for now. Feel free to use this bug report for further support (though I have very limited time recently, so please allow some time for reply).
